# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f1f2f2f4960d37f531ebb92ecd03d822685901dfec7370e434fb38af0cc1202cec11f6a52349731458062d5ae99d87a95709e3d987809476c0c85d72129d6ad

test:
  secret_key_base: 218262cf7d0a29a3d3ab2089e284e9c97f63ec663088e00de824f8c331578c5b160b8dcbd918aa4f98c2bd5463d544eebfb3dcd323539745209d34c46bee998e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
